### ISSUE TITLE
checkVersion() missing

### ISSUE THREAD

**Issue by AR-AR-AR** [LiveFlightApp/Connect-Windows#1]
checkVersion() is not found in the main form Load(). Are you missing a commit?

![image](https://cloud.githubusercontent.com/assets/15662513/11021732/93c3e4ce-8619-11e5-9fe3-1bdacd2512e7.png)

Thanks. (AR_AR on IF forum)

**Comment by carmichaelalonso** [comment]
Thanks! Skip this for now. I'm redoing this using the IFCTestApp as a base for UI (with WPF instead of Forms) which I should commit soon. Redoing my version management bits too :)
