### ISSUE TITLE
Heading commands sent too frequently

### ISSUE THREAD

**Issue by carmichaelalonso** [LiveFlightApp/Connect-Windows#6]
From Matt:

> I see in the log that within 200ms, a heading of something like 200.0 and then 200.02 were sent... I don't know if it makes a difference, but making it less frequent would probably help...

Should be a fairly simple solution, only send commands if difference of calculated heading is greater than 1 (at least)

**Comment by AR-AR-AR** [comment]
Might be fixed with commit https://github.com/LiveFlightApp/Connect-Windows/commit/c5920bd97fa5ee2c817b4085043ce24d52af4096

**Comment by carmichaelalonso** [comment]
@AR-AR-AR Shall I push to production and see what feedback we get?

**Comment by AR-AR-AR** [comment]
Sure. I ran it a few times and seemed to help.

**Comment by carmichaelalonso** [comment]
Looks like it has been fixed judging from this thread:
https://community.infinite-flight.com/t/autonav-altitude/91763/17?u=cameron

Thanks AR!
